import { createElement as h, useState } from 'react';
import './styles.css';
const issues=[['Overflowing drain near Community Hall','Drainage','In Progress','Sanitation & Drainage','28'],['Broken streetlight at Block C crossing','Streetlight','Assigned','Electrical Maintenance','17'],['Deep pothole on Main Market Road','Roads','Received','Roads & Works','41']];
const steps=['Received','Assigned','In Progress','Resolved'];
const E=(tag,props,...children)=>h(tag,props,...children);
function Card({data}){const [title,category,status,dept,count]=data;const n=steps.indexOf(status);return E('article',{className:'motion-issue'},E('div',{className:'issue-top'},E('span',{className:'category-dot'},category),E('span',{className:'status-pill'},status)),E('h3',null,title),E('p',null,'Jagmohan Nagar, Bhubaneswar'),E('small',null,'Routed to '+dept+' | '+count+' neighbour signals'),E('div',{className:'mini-lifecycle'},...steps.map((x,i)=>E('span',{key:x,className:i<=n?'done':''},E('i',null,i<n?'ok':String(i+1)),E('b',null,x)))));}
function App(){const [notice,setNotice]=useState('');const show=(x)=>{setNotice(x);setTimeout(()=>setNotice(''),2800)};const header=E('header',{className:'topbar'},E('div',{className:'brand'},E('span',{className:'brand-mark'},E('span'),E('span'),E('span')),E('span',null,'Civic',E('span',null,'Loop'))),E('nav',{className:'nav-links'},E('button',{className:'active'},'Home'),E('button',null,'Explore issues'),E('button',null,'Community budget')),E('button',{className:'button primary compact',onClick:()=>show('Report saved and routed to the civic response team.')},'Report an issue'));
               const hero=E('section',{className:'motion-hero'},E('div',null,E('div',{className:'eyebrow'},'Community-powered civic action'),E('h1',null,'See an issue.',E('br'),E('em',null,'Start a solution.')),E('p',null,'CivicLoop turns everyday reports into visible action and gives your neighbourhood a say in what gets fixed next.'),E('div',{className:'hero-actions'},E('button',{className:'button primary',onClick:()=>show('Report saved and routed to Sanitation & Drainage.')},'Report an issue'),E('button',{className:'button soft'},'Explore local issues'))),E('div',{className:'motion-map'},E('div',{className:'map-sun'}),E('div',{className:'pulsing-hotspot hotspot-one'},'12'),E('div',{className:'pulsing-hotspot hotspot-two'},'5'),E('div',{className:'pulsing-hotspot hotspot-three'},'7'),E('div',{className:'live-card'},E('small',null,'LIVE IN YOUR AREA'),E('b',null,'24 active reports'),E('button',null,'View map ->'))));
               const feed=E('section',{className:'section motion-section'},E('div',{className:'section-heading'},E('div',null,E('span',{className:'eyebrow'},'Transparent progress'),E('h2',null,'From report to resolution'),E('p',null,'Lifecycle status is visible on every local issue.'))),E('div',{className:'motion-issue-grid'},...issues.map((x,i)=>E(Card,{key:i,data:x}))));
               return E('div',{className:'app-shell civic-motion'},header,E('main',null,hero,feed),notice&&E('div',{className:'toast motion-toast'},E('strong',null,'OK'),notice,E('button',{onClick:()=>setNotice('')},'Close')));}
export default App;
